config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "map", to: "furries#map"
  get "my_furries", to: "furries#my_furries"

  # Defines the root path route ("/")
  root "furries#index"
  resources :bookings, only: [:index, :destroy, :update]

  resources :furries, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :furry
  belongs_to :user
  # validates :start_date, :end_date, presence: true # availability: true
  validate :end_date_after_start_date
  validates :status, presence: true
  enum status: [ :pending, :rejected, :accepted ]
  validates :total_cost, presence: true
  validates :dates, presence: true


  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    return errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/furrie.rb
class Furrie < ApplicationRecord
  belongs_to :user # dependent: :destroy
  has_many :bookings
  has_one_attached :photo
  validates :name, presence: true
  validates :description, presence: true
  validates :fursona, presence: true, inclusion: { in: %w[wolf fox dragon puppy cat racoon panda] }
  # validates :availability, default: true
end

app/models/furry.rb
class Furry < ApplicationRecord
  belongs_to :user # dependent: :destroy
  has_many :bookings, dependent: :destroy
  # has_many :users, through: :bookings, source: :user
  has_one_attached :photo
  validates :name, presence: true
  validates :description, presence: true
  validates :fursona, presence: true, inclusion: { in: %w[Wolf Fox Puppy Cat Raccoon Panda] }
  # validates :availability, default: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :energy, presence: { message: 'cannot be blank' }, numericality: { only_integer: true }
  validates :energy, numericality: { in: 1..5 }
  validates :cuddleable, presence: { message: 'cannot be blank' }, numericality: { only_integer: true }
  validates :cuddleable, numericality: { in: 1..5 }
  validates :tough_love, presence: { message: 'cannot be blank' }, numericality: { only_integer: true }
  validates :tough_love, numericality: { in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :furries, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :furries, source: :bookings
  # has_many :furries, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[destroy]

  def index
    @mybookings = current_user.bookings
    @myfurries = current_user.furries
    # key_skill if @myfurries[0].key_skill.nil?
    @my_furries_bookings = current_user.bookings_as_owner
  end


  def update
    @answer = params[:commit]
    @booking = Booking.find(params[:id])

    if @answer == "reject"
      @booking.rejected!

    elsif @answer == "accept"
      @booking.accepted!
    end
    redirect_to booking_path
  end

  def create
    @booking = Booking.new(booking_params)
    @furry = Furry.find(params[:furry_id])
    @booking.user = current_user
    @booking.furry = @furry
    @booking.status = "pending"

    days_booked = params[:booking][:dates].split(" to ")

    unless days_booked.empty?
      @booking.end_date = days_booked[1]
      @booking.start_date = days_booked[0]

      range = (@booking.end_date - @booking.start_date).to_i
      @booking.total_cost = range * @furry.price
      if @booking.save!
        redirect_to bookings_path
      else
        render "furries/show", status: :unprocessable_entity
      end

    else
      render "furries/show", status: :unprocessable_entity
    end
  end

  def destroy
    @furry_id = @booking.furry_id
    @booking.destroy
    redirect_to bookings_path
  end


  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:dates)
  end
end

app/controllers/furries_controller.rb
class FurriesController < ApplicationController
  before_action :set_furry, only: %i[show destroy]
  skip_before_action :authenticate_user!, only: %i[index show map]

  def index
    current_user.nil? ? @furries = Furry.all : @furries = Furry.where.not(user_id: current_user.id)
    if params[:search].present?
      @query = params[:search][:query]
      @furries = @furries.where("fursona ILIKE ?", "%#{@query}%")
    end
  end

  def map
    @furries = Furry.all
    @markers = @furries.geocoded.map do |furry|
      {
        lat: furry.latitude,
        lng: furry.longitude,
        info_window_html: render_to_string(partial: "furries/info_window", locals: { furry: furry }),
        marker_html: render_to_string(partial: "furries/marker", locals: { furry: furry })
      }
    end
  end

  def my_furries
    @furries = Furry.where(user_id: current_user.id)
    # key_skill if !@furries.nil? || @furries[0].key_skill.nil?
  end

  def show
    @booking = Booking.new
    @today = Date.today.to_s

    # Get an array of hashes witht he start and end date
    @dates_booked = @furry.bookings.map do |booking|
      { from: booking[:start_date], to: booking[:end_date] }
    end
  end

  def new
    @furry = Furry.new
  end

  def create
    @furry = Furry.new(furry_params)
    @furry.user = current_user
    # raise
    if @furry.save
      redirect_to furries_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @furry.destroy
    redirect_to furries_path
  end

  private

  def set_furry
    @furry = Furry.find(params[:id])
  end

  def furry_params
    params.require(:furry).permit(:name, :description, :price, :fursona, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # def map
  #   @furries = Furry.all
  #   @markers = @furries.geocoded.map do |furry|
  #     {
  #       lat: furry.latitude,
  #       lng: furry.longitude,
  #       info_window_html: render_to_string(partial: "furries/info_window", locals: { furry: furry }),
  #       marker_html: render_to_string(partial: "furries/marker", locals: { furry: furry })
  #     }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/bookings/_booking_status.html.erb
<% if booking.status == "rejected" %>
<div class= "status-red">Booking Declined</div>
<% elsif booking.status == "accepted" %>
<div class= "status-green">Booking Confirmed</div>
<% else %>
<div class= "status-purple">Pending Booking Confirmation</div>
<% end %>

app/views/bookings/_cards_booked_furries.html.erb
<div class="content" >
      <div class="row">
            <% my_furries_bookings.each do |booking| %>
                <div class="furries-card hvr-grow myDIV">
                  <div class="image">
                    <%= cl_image_tag booking.furry.photo.key, height: 350, width: 350, crop: :fill %>
                  </div>
                  <div class="content">

                    <div class="heading-and-text">
                      <div class="heading-and-icon">
                        <div class="heading"><%= booking.furry.name %></div>
                        <div class="icon-wrap">
                        </div>
                      </div>
                      <div class="content-text hide">
                        <%= render "update_booking", booking: booking %>
                      </div>
                    </div>
                    <%= link_to '', furry_path(booking.furry), class: 'card-link' %>
                  </div>
                </div>
            <% end %>
      </div>
    </div>
    <br>

app/views/bookings/_form.html.erb
<div data-controller="datepicker" data-datepicker-disabled-value="<%= @dates_booked.to_json %>" data-datepicker-min-date-value="<%= @today %>" data-datepicker-price-value="<%= furry.price.to_i %>">

<h3>Book this furry!</h3>
<h3 data-datepicker-target="total"></h3>
<%= simple_form_for [furry, booking] do |f| %>
  <%= f.input :dates, as: :string,  input_html: {
    data: {
      datepicker_target: "calendar",
      } } %>

  <%= f.submit 'Send booking request', class: "btn book-btn" %>
<% end %>
</div>

app/views/bookings/_update_booking.html.erb
<%= simple_form_for booking do |f| %>
  <%= f.submit :accept, class: "btn" %>
  <%= f.submit :reject, class: "btn" %>
<% end %>

app/views/bookings/index.html.erb
<%= render "shared/navbar"%>
<div id= "dashboard">
  <h1 >My Bookings</h1>


  <% unless @mybookings.empty? %>
    <% @mybookings.each do |booking| %>
      <div class="notification" style="<%= booking.rejected? ? 'border: 1px solid rgba(255, 0, 0, 0.5)' : 'border: rgba(0, 255, 0, 0.5);' %>" >
        <div> <%=cl_image_tag booking.furry.photo.key, height: 80, width: 80, crop: :fill%>
        </div>
        <div class="notification-content">
          <div>
            <p><small><%= booking.start_date %> to <%= booking.end_date %></small></p>
            <p><%= booking.furry.name %></p>
          </div>
          <h2 class="total-cost"><%=booking.total_cost.to_i%> €</h2>
        </div>
        <div class="notification-actions">
          <div>
            <%= render "booking_status", booking: booking %>
          </div>
          <div>
            <%= link_to "Cancel This Booking", booking_path(booking), data:{turbo_method: :delete}, class: "btn delete"%>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="notification">
      <h3>You havent booked an emotional support furry yet! </h3>
    </div>
  <% end %>
  <div class="pt-3">
  <h1>My furries that have been booked</h1>
  </div>
  <%unless @my_furries_bookings.empty? %>
    <% @my_furries_bookings.each do |booking| %>
      <div class="notification">
        <div> <%=cl_image_tag booking.furry.photo.key, height: 80, width: 80, crop: :fill%>
        </div>
        <div class="notification-content">
          <div>
            <p><small><%= booking.start_date %> - <%= booking.end_date %></small></p>
            <p><%= booking.furry.name %></p>
          </div>
          <h2 class="total-cost"><%=booking.total_cost.to_i%> €</h2>
        </div>
        <% if booking.pending? %>
        <div class="notification-actions d-flex flex-row justify-content-end">
          <div>
            <%= simple_form_for booking do |f| %>
              <%= f.submit :accept, class: "btn mx-3" %>
          </div>
          <div>
              <%= f.submit :reject, class: "btn mx-3" %>
            <% end %>
          </div>
        </div>
        <% else %>
            <%= render "booking_status", booking: booking %>
        <% end %>
      </div>
    <% end %>
  <%else%>
    <div class="notification">
      <h3>No bookings yet .. try spicing up your furries' profile.<h3>
    </div>
  <% end %>


</div>

app/views/furries/_cards.html.erb
<div class="content" >
      <div class="row">
            <% furries.each do |furry| %>
                <div class="furries-card hvr-grow myDIV">
                  <div class="image">
                    <%= cl_image_tag furry.photo.key, height: 350, width: 350, crop: :fill %>
                  </div>
                  <div class="content">
                    <div class="categories">
                      <div class="badge">
                          <div class="badge-base">
                            <div class="text"><%= furry.fursona %></div>
                          </div>
                      </div>
                      <div class="badge">
                          <div class="badge-base">
                            <div class="text"><%= furry.key_skill %></div>
                          </div>
                      </div>
                    </div>
                    <div class="heading-and-text">
                      <div class="heading-and-icon">
                        <div class="heading"><%= furry.name %></div>
                        <div class="icon-wrap">
                        </div>
                      </div>
                      <p class="content-text hide">
                        <%= furry.description %>
                      </p>
                      <div class="price"><%= furry.price.to_i%> <i class="fa-solid fa-euro-sign"></i></div>
                    </div>
                    <%= link_to '', furry_path(furry), class: 'card-link' %>
                  </div>
                </div>
            <% end %>
      </div>
    </div>

app/views/furries/_dashboard.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-paw fa-xl" style="color: #7743db;"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
            <%= simple_form_for :search, url: root_path, method: :get do |f| %>
              <div class="search-form-control form-group">
                <input class="form-control string required" type="text" name="search[query]" id="search_query" />
                <button name="button" type="submit" class="btn btn-flat">
                  <i class="fas fa-search"></i> Search
                </button>
              </div>
            <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "dashboard", "root_path" , class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/2/2c/Default_pfp.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/furries/_form.html.erb
<%= simple_form_for(furry) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :key_skill, collection: %w(Cuddleable Energy ToughLove) %>
  <%= f.input :cuddleable %>
  <%= f.input :energy %>
  <%= f.input :tough_love %>
  <%= f.input :fursona, collection: %w(Wolf Fox Puppy Cat Raccoon Panda) %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn" %>
<% end %>

app/views/furries/_info_window.html.erb
<h2><%= link_to furry.name, furry_path(furry) %></h2>
<p><%= furry.address %></p>

app/views/furries/_marker.html.erb
<div class="badge custom-circle bg-primary fs-6">
  <% case furry.fursona %>
    <% when "Cat" %>
      <%= "🐱" %>
    <% when "Puppy" %>
      <%= "🐶" %>
    <% when "Wolf" %>
      <%= "🐺" %>
    <% when "Panda" %>
      <%= "🐼" %>
    <% when "Raccoon" %>
      <%= "🦝" %>
    <% else %>
      <%= "🤡" %>
  <% end %>
</div>

app/views/furries/index.html.erb
<div class="container" id="index-container">
    <%= render "cards", furries: @furries%>
</div>

app/views/furries/map.html.erb
<div class="container" id="index-container">
  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/furries/my_furries.html.erb
<div class="container" id="index-container">

<%= link_to  "+ Add new furry", new_furry_path, class: "btn add-furry" %>
    <%= render "cards", furries: @furries%>
</div>

app/views/furries/new.html.erb
<div class="container col-6 new-furry-page">
  <h1>Create a new Furry</h1>
  <%= render "form", furry: @furry %>
</div>

app/views/furries/show.html.erb
<div class="container">
<div class="d-flex" id="show-page" justify-items-space-around>
  <div class="info-furry d-flex">
    <div class="px-3 col-6">
      <%= cl_image_tag @furry.photo.key, height: 400, width: 400, crop: :fill %>
    </div>
      <div class="d-flex flex-column">
        <div class="furry-description col-9">
          <div class="d-inline-block m-3">
            <h1><%= @furry.name %></h1>
          </div>
             <p><%= @furry.description %></p>
             </div>
              <div>
                <h2><%= @furry.price.to_i %> <i class="fa-solid fa-euro-sign"></i> p. day</h2>
              </div>
                <p>Energy
                <% @furry.energy.times do %>
                  <i class="fa-solid fa-star" style="color: #ffd43b;"></i>
                <% end %>
                <% (5 - @furry.energy).times do %>
                  <i class="fa-regular fa-star" style="color: #ffd43b;"></i>
                <% end %>
                </p>
                <p>Cuddleable
                <% @furry.cuddleable.times do %>
                  <i class="fa-solid fa-star" style="color: #ffd43b;"></i>
                <% end %>
                <% (5 - @furry.cuddleable).times do %>
                  <i class="fa-regular fa-star" style="color: #ffd43b;"></i>
                <% end %>
                </p>
                <p>Tough Love
                <% @furry.tough_love.times do %>
                  <i class="fa-solid fa-star" style="color: #ffd43b;"></i>
                <% end %>
                <% (5 - @furry.tough_love).times do %>
                  <i class="fa-regular fa-star" style="color: #ffd43b;"></i>
                <% end %>
                </p>
            <div class="book-card">
              <div class="p-6 form-show col-6">
                <%= render "bookings/form", booking: @booking, furry:@furry %>
              </div>
            </div>

        </div>
      </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warm & Furries</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="https://res.cloudinary.com/dbd4uen7z/image/upload/v1700660034/favicon.png">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>


  <body>
    <%# <div data-controller="toggle" > %>
      <%= render "shared/navbar" %>
        <%= yield %>
    <%# </div> %>
    <%= render "shared/footer" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/map.html.erb
<div class="container-fluid" id="index-container">
  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> by Jamie, Zoe & Iratxe</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky px-3">
  <%# <div class="d-flex justify-content-between"> %>
  <div class="d-flex">
  <div class="logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa-solid fa-paw fa-beat fa-xl" style="color: #7743db;"></i>
      <% end %>
    </div>
    <div class="page-name">
    <h2>Warm & Furries</h2>
    </div>
  </div>
    <div class="nav-item search">
      <%= simple_form_for :search, url: root_path, method: :get do |f| %>
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="search[query]" id="search_query" />
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i>
          </button>
        </div>
      <% end %>
    </div>

      <div class="user-dashboard d-flex">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <div class="nav-item active">
          <% if params[:controller] == "furries" && params[:action] == "index"%>
            <%= link_to "Show Map", "map", class: "btn nav-link" %>
          <% elsif params[:controller] == "furries" && params[:action] == "map"%>
            <%= link_to "Show Furries", "furries", class: "btn nav-link" %>
          <% end %>
        </div>

          <li class="nav-item active mx-3">
          <% if params[:controller] == "bookings" && params[:action] == "index"%>
            <%= link_to "Home", root_path, class: "btn nav-link" %>

          <% else %>
            <%= link_to "Dashboard", bookings_path, class: "btn nav-link" %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/emmvs", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown";>
              <%#= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "My Furries", my_furries_path, class: "dropdown-item" %>

              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>

            </div>
          </li>
        <% else %>
          <%# <li class="nav-item"> %>
          <div class="nav-item active">
          <% if params[:controller] == "furries" && params[:action] == "index"%>
            <%= link_to "Show Map", "map", class: "btn nav-link" %>

          <% end %>
        </div>
          <div data-controller="toggle" >

            <button data-toggle-target="button" class="btn" data-action="click->toggle#show">Log in</button>
            <div class="d-none" data-toggle-target="toggleableElement">
              <%= render "devise/sessions/new" %>
          </div>
          <%# </li> %>
        <% end %>
      </ul>

    </div>
    </div>
</div>